/*
    JW Control extension for QElectroTech

    Smart Snap V2 deliberately avoids a global qApp event filter. The latest
    geometry/routing implementation lives in jwsmartconductorsnaplegacy.cpp,
    but its automatic global startup hook is disabled here. The filter is then
    attached only to DiagramView and its viewport.
*/

#include "diagramview.h"

#include <QApplication>
#include <QCoreApplication>
#include <QTimer>

// QCoreApplication is already included above, so the include guard prevents
// the legacy source from redefining this macro. Suppressing the startup macro
// is enough to keep its qApp-wide installer from ever running.
#ifdef Q_COREAPP_STARTUP_FUNCTION
#undef Q_COREAPP_STARTUP_FUNCTION
#endif
#define Q_COREAPP_STARTUP_FUNCTION(AFUNC)
#include "jwsmartconductorsnaplegacy.cpp"
#undef Q_COREAPP_STARTUP_FUNCTION

namespace {

class JwSmartConductorSnapViewBinder final : public QObject
{
    public:
        explicit JwSmartConductorSnapViewBinder(QObject *parent = nullptr) :
            QObject(parent)
        {
            m_scan_timer.setInterval(400);
            m_scan_timer.setSingleShot(false);
            connect(&m_scan_timer, &QTimer::timeout,
                    this, [this]() { bindAvailableDiagramViews(); });
            m_scan_timer.start();

            if (qApp)
            {
                connect(qApp, &QApplication::focusChanged,
                        this,
                        [this](QWidget *, QWidget *) {
                            bindAvailableDiagramViews();
                        });
            }

            QTimer::singleShot(0, this,
                               [this]() { bindAvailableDiagramViews(); });
        }

    private:
        void bindAvailableDiagramViews()
        {
            if (!s_smart_conductor_snap_filter) {
                return;
            }

            const QWidgetList widgets = QApplication::allWidgets();
            for (QWidget *widget : widgets)
            {
                auto *view = qobject_cast<DiagramView *>(widget);
                if (!view || !view->viewport()) {
                    continue;
                }

                if (view->property("jw.smartSnapV2.bound").toBool()) {
                    continue;
                }

                // Mouse events are generated by the viewport. Escape and
                // related key events are normally delivered to the view. No
                // other widgets (QMenu, dialogs, docks, the application, ...)
                // are observed by Smart Snap V2.
                view->viewport()->installEventFilter(
                        s_smart_conductor_snap_filter);
                view->installEventFilter(
                        s_smart_conductor_snap_filter);
                view->setProperty("jw.smartSnapV2.bound", true);
            }
        }

    private:
        QTimer m_scan_timer;
};

JwSmartConductorSnapViewBinder *s_smart_snap_view_binder = nullptr;

void installJwSmartConductorSnapV2()
{
    if (!qApp || s_smart_snap_view_binder) {
        return;
    }

    if (!s_smart_conductor_snap_filter)
    {
        s_smart_conductor_snap_filter =
                new JwSmartConductorSnapFilter(qApp);
    }

    s_smart_snap_view_binder =
            new JwSmartConductorSnapViewBinder(qApp);
}

void registerJwSmartConductorSnapV2()
{
    QCoreApplication::addPreRoutine(installJwSmartConductorSnapV2);
}

} // namespace

Q_CONSTRUCTOR_FUNCTION(registerJwSmartConductorSnapV2)
